#!/bin/sh

# TODO make better error logging.
solution=$(head -c 41 < $level_dir/prg_x.bin | tail -c 1 | xxd | cut -d' ' -f2)
cat $level_dir/in_i.bin - $level_dir/out_i.bin |
$interpreter |
head -c 122 |
tail -c 1 |
xxd | cut -d' ' -f2 |
    {
read result
test $result = $solution
} ||
echo KO

