# unit_tests are generated by including the corresponding source file
# and appending a main.
# Thus, they may depend not depend on the corresponding object file,
# as that would be duplicating the source.
# Yet the may rely on other object files.
# Hence the present solution, taking in the set of object files
# and replacing the object of the file being tested by it's test.
# 
# Having the test source including the origin header rather than it's source
# is a much more sensible approach where my issue is a non issue.
# But I wanted to test private items (or I wanted to not include in headers
# some of the things I do test, is an other way to look at it)
use warnings;
use strict;

my ($src) = @ARGV;
(my $obj = $src) =~ s"^unit_tests/src(.*)\.c$"obj$1.o"; #"# my linter is in shambles
while(my $line = <STDIN>) {
    $line =~ s/$obj/$src/;
    print "$line" ;
}

